 # exception---

 # abnormal event during the execution program


print ("answer")

try:
    a = 10 / 0
except ZeroDivisionError:
    print("zero division")

print("try again !??")


# b = 5 / 0